#pragma once
#include "Mashenka/Renderer/Texture.h"

namespace Mashenka
{
    class OpenGLTexture2D : public Texture2D
    {
    public:
        // Create
        OpenGLTexture2D(const std::string& path);
        virtual ~OpenGLTexture2D();

        // Getters
        virtual uint32_t GetWidth() const override { return m_Width; }
        virtual uint32_t GetHeight() const override { return m_Height; }

        virtual void Bind(uint32_t slot = 0) const override;

    private:
        std::string m_Path;
        uint32_t m_Width, m_Height;
        uint32_t m_RendererID; //generated by OpenGL with glGenTextures
        
    };

}
